#!/bin/sh -xeu

self="$(realpath -- "$0" || printf %s "$0")"
cd -- "$(dirname -- "$self")"

gitdir="$(git rev-parse --show-toplevel)"
cd -- "$gitdir"

# HACK: Work around https://github.com/azz/pretty-quick/issues/164
exec npx -p prettier@^2 -p pretty-quick pretty-quick
